mcp:
  servers:
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "~/sandbox"]
      description: "Provide your agent with access to your local file system."
    git:
      command: "uvx"
      args: ["mcp-server-git"]
      description: "Git repository tools for reading, searching, and manipulating repos."

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4.1-nano
